---
- hosts: all
  user: deploy
  sudo: True
  gather_facts: True
  vars_files:
    - vars/defaults.yml
    - vars/{{ 'testing' if testing is defined else 'user' }}.yml
  roles:
    - base
    - common
    #- tarsnap
    - monitoring
