---
# Defines tasks applicable across all machines in the infrastructure.

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Install necessities and nice-to-haves
  apt: pkg=$item state=installed
  with_items:
    - sudo
    - vim
    - htop
    - iftop
    - iotop
    - mosh
    - zsh
    - git
    - ruby1.9.3
    - screen
    - apache2
    - build-essential
    - apticron
    - update-notifier-common
    - debian-goodies

- name: Install ntp
  apt: pkg=ntp state=installed

- name: Configure ntp
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntp

- name: Ensure ntpd is running and enabled
  service: name=ntp state=started enabled=yes

- name: Disable default Apache site
  command: a2dissite default removes=/etc/apache2/sites-enabled/default
  notify: restart apache

- include: encfs.yml tags=encfs
- include: users.yml tags=users
- include: ssl.yml tags=ssl
- include: ferm.yml tags=ferm
- include: security.yml tags=security
