---

- name: Do not send ICMP redirects
  sysctl:
    name="net.ipv4.conf.all.send_redirects"
    value=0
    sysctl_set=yes
    state=present
    reload=yes

- name: Do not accept IP source route packets
  sysctl:
    name="net.ipv4.conf.all.accept_source_route"
    value=0
    sysctl_set=yes
    state=present
    reload=yes

- name: Prevent ICMP broadcast (smurf amplifier) storms
  sysctl:
    name="net.ipv4.icmp_echo_ignore_broadcasts"
    value=1
    sysctl_set=yes
    state=present
    reload=yes
